# Generated by Django 3.0 on 2021-07-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('med', models.CharField(max_length=20)),
                ('time', models.BooleanField(choices=[(1, 'morning'), (2, 'Afternoon'), (3, 'Night')], default=False)),
            ],
        ),
    ]
