# Generated by Django 3.0 on 2021-07-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_medic'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='pid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Patients'),
            preserve_default=False,
        ),
    ]
