# Generated by Django 3.0 on 2021-07-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_remove_medic_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='time',
            field=models.IntegerField(choices=[(1, 'morning'), (2, 'Afternoon'), (3, 'Night')], default=False),
        ),
    ]
