# Generated by Django 3.0 on 2021-07-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_auto_20210724_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medic',
        ),
    ]
