# Generated by Django 3.0 on 2021-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_medic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='time',
            field=models.IntegerField(choices=[(1, 'morning'), (2, 'Afternoon'), (3, 'Night')], max_length=10),
        ),
    ]
